#spring.profiles.active=produccion
#-----DESCOMENTAR "spring.profiles.active=produccion" para compilar y subir a producción
spring.profiles.active=local
#-----DESCOMENTAR spring.profiles.active=local para trabajar con las variables de entorno local 
spring.http.multipart.max-request-size=8MB
spring.http.multipart.max-file-size=8MB