# CONFIGURACION DE DATASOURCE
SPRING.DATASOURCE.URL=jdbc:sqlserver://172.16.1.85:1433;databaseName=academia3000_john;user=;password=
SPRING.DATASOURCE.DRIVER-CLASS-NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
SPRING.DATASOURCE.JNDI-NAME=java:jboss/datasources/ConsultaDS

# CONFIGURACION DE SPRING JPA
SPRING.JPA.SHOW-SQL=false
#SPRING.JPA.PROPERTIES.HIBERNATE.FORMAT_SQL=true
SPRING.JPA.HIBERNATE.DDL-AUTO=none
SPRING.JPA.PROPERTIES.HIBERNATE.GLOBALLY_QUOTED_IDENTIFIERS=true
LOGGING.LEVEL.ORG.HIBERNATE.SQL=debug
SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.SQLServer2008Dialect
SPRING.JPA.HIBERNATE.NAMING.PHYSICAL-STRATEGY=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# CONFIGURACION SPRING MAIN
SPRING.MAIN.ALLOW-BEAN-DEFINITION-OVERRIDING=true

# CONFIGURACION SPRING JACKSON
SPRING.JACKSON.TIME-ZONE=America/Bogota
SPRING.JACKSON.LOCALE=es_CO

# CONFIGURACION DE FEIGN DE SERVICIO DE ARCHIVO Y FOTO LOCAL
FEIGN.URL=http://dana.usco.edu.co/GestionArchivoBack
FEIGN.FOTO.URL=http://dana.usco.edu.co/GestionFotoBack
